# Generated by Django 3.0.5 on 2020-04-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('campaign_id', models.CharField(max_length=20)),
                ('campaign_name', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=10)),
                ('lead_id', models.CharField(max_length=10)),
                ('units', models.CharField(max_length=4)),
                ('PM', models.CharField(max_length=10)),
                ('DA', models.CharField(max_length=10)),
                ('notes', models.TextField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-delivery_date', '-campaign_id'),
            },
        ),
    ]
